- name: Ensure the target directory exists
  become: yes
  ansible.builtin.file:
    path: /home/sreram/temp
    state: directory
    mode: '0755'

- name: Copy validate.sh script to target server
  become: yes
  ansible.builtin.copy:
    src: /home/sreram/Ansible/redhat/validate.sh
    dest: /home/sreram/temp/validate.sh
    mode: '0755'

- name: Convert validate.sh to Unix format
  become: yes
  ansible.builtin.shell: sed -i 's/\r$//' /home/sreram/temp/validate.sh

- name: Run validate.sh script before patching and capture output
  ansible.builtin.shell: "/home/sreram/temp/validate.sh"
  register: validate_status
  failed_when: validate_status.rc != 0

- name: Save validate.sh output to a text file
  become: yes
  ansible.builtin.copy:
    content: "{{ validate_status.stdout }}"
    dest: /home/sreram/temp/pldfanc0429pmdfadulh01_before_30_07_2024.txt

- name: Debug output of validate.sh
  debug:
    msg: "{{ validate_status.stdout }}"

- name: Create VM snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ hostvars['vm1']['vcenter_host'] }}"
    username: "{{ hostvars['vm1']['vcenter_user'] }}"
    password: "{{ hostvars['vm1']['vcenter_password'] }}"
    validate_certs: no
    datacenter: "Madurai"
    folder: "/VM-Automation/"
    name: "redhat01"
    snapshot_name: "redhat01"
    description: "Snapshot before patching"
    state: present
  delegate_to: localhost
  vars:
    ansible_python_interpreter: /home/sreram/Ansible/redhat/lib/bin/python3
